[package]
org = "ballerina"
name = "serdes"
version = "0.1.0-alpha7"

[[platform.java11.dependency]]
path = "../serdes-native/build/libs/serdes-native-0.1.0-alpha7-SNAPSHOT.jar"
groupId = "io.ballerina.stdlib.serdes"
artifactId = "serdes"
version = "0.1.0-alpha7-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.14.0.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.14.0"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-util-3.14.0.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java-util"
version = "3.14.0"
